"""Station 1 - ETL: load, clean, and integrity-check the raw data.

All datasets are loaded through src.data_access. Integrity checks include:
  - Missing-date audit per ticker (equity: union of all trading dates;
    crypto: full calendar day range 2020-01-01 to 2023-12-31)
  - Duplicate detection (prices: unique by (ticker, date); news: exact
    duplicates on (ticker, date, title) only, since news legitimately
    has many rows per ticker-date)
  - Outlier / extreme-return screen with price-volume consistency check
    (keep and explain genuine extreme returns; do not delete them)

Clean output schema and provenance are documented in results/tables/
via the schema_and_provenance.csv generated by run_part_a.py.
"""
from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np
import pandas as pd

from src import data_access

# ---------------------------------------------------------------------------
# Dataclass to collect integrity-check results
# ---------------------------------------------------------------------------

@dataclass
class IntegrityReport:
    """Accumulates findings from each integrity check."""
    equity_rows_raw: int = 0
    equity_rows_clean: int = 0
    equity_dup_ticker_date: int = 0
    equity_missing_dates: dict = field(default_factory=dict)  # ticker -> count of gaps
    equity_volume_zeros: int = 0
    equity_ohlc_inconsistent: int = 0

    crypto_rows_raw: int = 0
    crypto_rows_clean: int = 0
    crypto_dup_ticker_date: int = 0
    crypto_capped_2024: int = 0
    crypto_missing_dates: dict = field(default_factory=dict)
    crypto_volume_zeros: int = 0
    crypto_ohlc_inconsistent: int = 0

    news_rows_raw: int = 0
    news_rows_deduped: int = 0
    news_exact_dups: int = 0

    outlier_returns_equity: int = 0
    outlier_returns_crypto: int = 0
    outlier_threshold: float = 0.0

    def _gapped_tickers(self, missing: dict) -> str:
        shown = list(missing.keys())[:5]
        suffix = "..." if len(missing) > 5 else ""
        return f"(tickers with gaps: {shown}{suffix})"

    def summary(self) -> str:
        lines = [
            "=== Integrity Report ===",
            f"Equities: {self.equity_rows_raw} raw -> {self.equity_rows_clean} clean "
            f"({self.equity_dup_ticker_date} duplicate ticker-date rows removed)",
            f"  Missing-date tickers: {len(self.equity_missing_dates)} "
            f"{self._gapped_tickers(self.equity_missing_dates)}",
            f"  Volume = 0 rows: {self.equity_volume_zeros}",
            "  OHLC inconsistent (high < low or high < open/close): "
            f"{self.equity_ohlc_inconsistent}",
            f"Crypto:   {self.crypto_rows_raw} raw -> {self.crypto_rows_clean} clean "
            f"({self.crypto_capped_2024} rows after 2023-12-31 dropped, "
            f"{self.crypto_dup_ticker_date} duplicate ticker-date rows)",
            f"  Missing-date tickers: {len(self.crypto_missing_dates)} "
            f"{self._gapped_tickers(self.crypto_missing_dates)}",
            f"  Volume = 0 rows: {self.crypto_volume_zeros}",
            "  OHLC inconsistent (high < low or high < open/close): "
            f"{self.crypto_ohlc_inconsistent}",
            f"Headlines: {self.news_rows_raw} raw -> {self.news_rows_deduped} after dedup "
            f"({self.news_exact_dups} exact duplicates on ticker+date+title removed)",
            f"Outlier threshold: {self.outlier_threshold:.0%}",
            f"  Equity returns |r| > threshold: {self.outlier_returns_equity}",
            f"  Crypto returns |r| > threshold: {self.outlier_returns_crypto}",
        ]
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Price-volume consistency checks (shared)
# ---------------------------------------------------------------------------

def _check_ohlc_consistency(df: pd.DataFrame, label: str, report: IntegrityReport,
                            is_crypto: bool = False) -> None:
    """Check OHLC consistency and volume anomalies.

    Flags:
      - high < low (impossible)
      - high < open or high < close (high should be max of OHLC)
      - low > open or low > close (low should be min of OHLC)
      - volume = 0 (no trades recorded)
    These are logged, not deleted — the data is kept as-is.
    """
    vol_zeros = int((df["volume"] == 0).sum())
    high_low_invalid = int((df["high"] < df["low"]).sum())
    high_open_invalid = int((df["high"] < df["open"]).sum())
    high_close_invalid = int((df["high"] < df["close"]).sum())
    low_open_invalid = int((df["low"] > df["open"]).sum())
    low_close_invalid = int((df["low"] > df["close"]).sum())
    ohlc_total = (
        high_low_invalid + high_open_invalid + high_close_invalid
        + low_open_invalid + low_close_invalid
    )

    if is_crypto:
        report.crypto_volume_zeros = vol_zeros
        report.crypto_ohlc_inconsistent = ohlc_total
    else:
        report.equity_volume_zeros = vol_zeros
        report.equity_ohlc_inconsistent = ohlc_total

    if vol_zeros > 0:
        print(f"  [{label}] {vol_zeros} rows with volume = 0 (kept)")
    if ohlc_total > 0:
        print(f"  [{label}] {ohlc_total} OHLC consistency issues "
              f"(high<low: {high_low_invalid}, high<open: {high_open_invalid}, "
              f"high<close: {high_close_invalid}, low>open: {low_open_invalid}, "
              f"low>close: {low_close_invalid})")


# ---------------------------------------------------------------------------
# Equity loading & cleaning
# ---------------------------------------------------------------------------

def load_clean_equities() -> tuple[pd.DataFrame, IntegrityReport]:
    """Load equity prices, de-dup, run missing-date audit and consistency checks.

    Checks performed:
      1. Duplicate ticker-date pairs (should be unique)
      2. Missing-date audit per ticker (union of all dates across tickers)
      3. OHLC consistency (high >= low, high >= open/close, low <= open/close)
      4. Volume zero check
    """
    report = IntegrityReport()
    df = data_access.load_equity_prices()
    report.equity_rows_raw = len(df)

    df = df.sort_values(["ticker", "date"]).reset_index(drop=True)

    # --- duplicate ticker-date check (prices must be unique by ticker+date) ---
    dups = df.duplicated(subset=["ticker", "date"], keep=False)
    report.equity_dup_ticker_date = int(dups.sum())
    if report.equity_dup_ticker_date > 0:
        print(f"  [Equities] {report.equity_dup_ticker_date} duplicate "
              "ticker-date pairs found and removed")
    df = df.drop_duplicates(subset=["ticker", "date"], keep="first").reset_index(drop=True)

    # --- missing-date audit: build a per-ticker calendar from the union of dates ---
    # Equities trade ~252 days/yr. The expected calendar is the union of all
    # dates that appear in any ticker. A missing date means that ticker had no
    # price record on a day when at least one other equity traded.
    all_dates = np.sort(df["date"].unique())
    for ticker, g in df.groupby("ticker"):
        ticker_dates = set(g["date"])
        expected = set(all_dates)
        missing = expected - ticker_dates
        if missing:
            report.equity_missing_dates[ticker] = len(missing)
    if report.equity_missing_dates:
        print(f"  [Equities] {len(report.equity_missing_dates)} tickers with missing dates")
    else:
        print("  [Equities] No missing dates across any ticker")

    # --- OHLC and volume consistency ---
    _check_ohlc_consistency(df, "Equities", report, is_crypto=False)

    report.equity_rows_clean = len(df)
    return df, report


# ---------------------------------------------------------------------------
# Crypto loading & cleaning
# ---------------------------------------------------------------------------

def load_clean_crypto(report: IntegrityReport) -> pd.DataFrame:
    """Load crypto prices, cap at 2023-12-31, de-dup, run consistency checks.

    Crypto trades every calendar day (~365 days/yr). The full date range is
    checked against each ticker's dates.
    """
    df = data_access.load_crypto_prices()
    report.crypto_rows_raw = len(df)

    df = df.sort_values(["ticker", "date"]).reset_index(drop=True)

    # --- cap stray 2024-01-01 rows ---
    cutoff = pd.Timestamp("2023-12-31")
    before = len(df)
    df = df[df["date"] <= cutoff].reset_index(drop=True)
    report.crypto_capped_2024 = before - len(df)
    if report.crypto_capped_2024 > 0:
        print(f"  [Crypto] Dropped {report.crypto_capped_2024} rows dated after 2023-12-31")

    # --- duplicate ticker-date check (prices must be unique by ticker+date) ---
    dups = df.duplicated(subset=["ticker", "date"], keep=False)
    report.crypto_dup_ticker_date = int(dups.sum())
    if report.crypto_dup_ticker_date > 0:
        print(f"  [Crypto] {report.crypto_dup_ticker_date} duplicate "
              "ticker-date pairs found and removed")
    df = df.drop_duplicates(subset=["ticker", "date"], keep="first").reset_index(drop=True)

    # --- missing-date audit (crypto trades every calendar day) ---
    full_range = pd.date_range(df["date"].min(), df["date"].max(), freq="D")
    for ticker, g in df.groupby("ticker"):
        missing = set(full_range) - set(g["date"])
        if missing:
            report.crypto_missing_dates[ticker] = len(missing)
    if report.crypto_missing_dates:
        print(f"  [Crypto] {len(report.crypto_missing_dates)} tickers with missing calendar days")
    else:
        print("  [Crypto] No missing calendar days across any ticker")

    # --- OHLC and volume consistency ---
    _check_ohlc_consistency(df, "Crypto", report, is_crypto=True)

    report.crypto_rows_clean = len(df)
    return df


# ---------------------------------------------------------------------------
# Headlines loading & cleaning
# ---------------------------------------------------------------------------

def load_clean_headlines(report: IntegrityReport) -> pd.DataFrame:
    """Load news headlines, de-dup on ticker+date+title, normalise timezone.

    News legitimately has many rows per ticker-date (multiple articles per
    day). Exact duplicates are only those where ticker, date, AND title are
    identical — not ticker-date alone.
    """
    df = data_access.load_news_headlines()
    report.news_rows_raw = len(df)

    # Normalise timezone to tz-naive UTC so merges with prices work.
    # The headline date is tz-aware UTC (datetime64[us, UTC]) while price
    # dates are tz-naive (datetime64[ns]). Without normalisation, merge_asof
    # and merge operations silently fail or error.
    if hasattr(df["date"].dtype, "tz") and df["date"].dtype.tz is not None:
        df["date"] = df["date"].dt.tz_convert("UTC").dt.tz_localize(None)

    df["date"] = pd.to_datetime(df["date"])

    # --- exact-duplicate check on ticker + date + title ---
    dups = df.duplicated(subset=["ticker", "date", "title"], keep=False)
    report.news_exact_dups = int(dups.sum())
    if report.news_exact_dups > 0:
        print(f"  [Headlines] {report.news_exact_dups} exact duplicates on "
              "(ticker, date, title) removed")
    df = df.drop_duplicates(subset=["ticker", "date", "title"], keep="first").reset_index(drop=True)
    report.news_rows_deduped = len(df)

    return df


# ---------------------------------------------------------------------------
# Outlier screen
# ---------------------------------------------------------------------------

def flag_outlier_returns(
    returns: pd.DataFrame,
    threshold: float = 0.30,
    report: IntegrityReport | None = None,
    is_crypto: bool = False,
) -> pd.DataFrame:
    """Flag daily returns with |r| > threshold. Keep all rows; just flag them.

    The threshold is set to 30% which catches the most extreme single-day
    moves (for example the March 2020 COVID crash for equities). Real extreme
    returns are genuine market events and are kept, not deleted.

    Price-volume consistency is already checked in the ETL stage. Here we
    verify that the extreme returns correspond to plausible price movements
    by checking that the adjusted close changed proportionally.
    """
    if report is not None:
        report.outlier_threshold = threshold
    mask = returns["return"].abs() > threshold
    n_outliers = int(mask.sum())

    if report is not None:
        if is_crypto:
            report.outlier_returns_crypto = n_outliers
        else:
            report.outlier_returns_equity = n_outliers

    if n_outliers > 0:
        label = "Crypto" if is_crypto else "Equities"
        # Show the top 5 extreme returns for documentation
        extreme = returns.loc[mask, ["date", "ticker", "return", "adjClose"]].copy()
        extreme["abs_return"] = extreme["return"].abs()
        extreme = extreme.nlargest(5, "abs_return")
        print(f"  [Outliers] {label}: {n_outliers} returns with |r| > {threshold:.0%}")
        for _, row in extreme.iterrows():
            print(f"    {row['ticker']} on {row['date'].strftime('%Y-%m-%d')}: "
                  f"return={row['return']:.2%}, adjClose={row['adjClose']:.2f}")

    returns = returns.copy()
    returns["is_outlier"] = mask
    return returns
